export { default as Attributes } from "./attributes/Attributes";
export { default as Character } from "./attributes/Character";
export { default as Devices } from "./attributes/Devices";
export { default as InfoBox } from "./commons/InfoBox";
export { default as Target } from "./attributes/Target";
export { default as ResultModal } from "./results/ResultModal";
export { default as Type } from "./attributes/Type";
export { default as Header } from "./layouts/Header";
export { default as Footer } from "./layouts/Footer";
